config/routes.rb
Rails.application.routes.draw do
  resources :posts

  devise_for :users
  
  root to: 'home#index'

  resources :profiles do
    post :import, on: :collection
    delete :destroy_all, on: :collection
  end

  resources :invoices do
    post :import, on: :collection
    delete :destroy_all, on: :collection
    post :send_emails, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  scope :has_supplier, -> { pluck(:supplier_name).uniq } 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :feature_image
end

app/models/profile.rb
class Profile < ApplicationRecord
  bind_inum :kind, ProfileKind
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!

  def index
    @invoices = Invoice.all
  end

  def import
    CsvMasterDataService.new(Invoice, invoice_file_params).import_csv
    redirect_to invoices_url, notice: 'Data imported'
  end

  def destroy_all
    Invoice.destroy_all
    redirect_to invoices_url, notice: 'All data destroyed'
  end

  def invoice_file_params
    params[:invoice][:file]
  end

  def send_emails
    Invoice.has_supplier.each do |supplier|
      InvoiceMailer.send_to_supplier(supplier).deliver_later
    end

    redirect_to invoices_url, notice: 'Email has been sent'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :user_id, :feature_image)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @profiles = Profile.all
  end

  def import
    CsvMasterDataService.new(Profile, profile_file_params).import_csv
    redirect_to profiles_url, notice: 'Data imported'
  end

  def destroy_all
    Profile.destroy_all
    redirect_to profiles_url, notice: 'All data destroyed'
  end

  def profile_file_params
    params[:profile][:file]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<div class="husky_body">
  <div class="husky">
    <div class="mane">
      <div class="coat"></div>
    </div>
    <div class="body">
      <div class="head">
        <div class="ear"></div>
        <div class="ear"></div>
        <div class="face">
          <div class="eye"></div>
          <div class="eye"></div>
          <div class="nose"></div>
          <div class="mouth">
            <div class="lips"></div>
            <div class="tongue"></div>
          </div>
        </div>
      </div>
      <div class="torso"></div>
    </div>
    <div class="legs">
      <div class="front-legs">
        <div class="leg"></div>
        <div class="leg"></div>
      </div>
      <div class="hind-leg">
      </div>
    </div>
    <div class="tail">
      <div class="tail">
        <div class="tail">
          <div class="tail">
            <div class="tail">
              <div class="tail">
                <div class="tail"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<svg xmlns="http://www.w3.org/2000/svg" version="1.1" style="display:none">
  <defs>

    
    <filter id="squiggly-0">
      <feTurbulence id="turbulence" baseFrequency="0.02" numOctaves="3" result="noise" seed="0"/>
      <feDisplacementMap id="displacement" in="SourceGraphic" in2="noise" scale="2" />
    </filter>
    <filter id="squiggly-1">
      <feTurbulence id="turbulence" baseFrequency="0.02" numOctaves="3" result="noise" seed="1"/>
<feDisplacementMap in="SourceGraphic" in2="noise" scale="3" />
    </filter>
    
    <filter id="squiggly-2">
      <feTurbulence id="turbulence" baseFrequency="0.02" numOctaves="3" result="noise" seed="2"/>
<feDisplacementMap in="SourceGraphic" in2="noise" scale="2" />
    </filter>
    <filter id="squiggly-3">
      <feTurbulence id="turbulence" baseFrequency="0.02" numOctaves="3" result="noise" seed="3"/>
<feDisplacementMap in="SourceGraphic" in2="noise" scale="3" />
    </filter>
    
    <filter id="squiggly-4">
      <feTurbulence id="turbulence" baseFrequency="0.02" numOctaves="3" result="noise" seed="4"/>
<feDisplacementMap in="SourceGraphic" in2="noise" scale="1" />
    </filter>
  </defs> 
</svg>

app/views/invoices/index.html.erb
<div class="max-w-6xl m-auto">
  <div class="flex items-center justify-between pb-4 mb-4 border-b">
    <h1 class="text-xl font-bold mb-0 uppercase text-gray-500">Profiles</h1>
    <div>
      <%= link_to 'Delete All Data',destroy_all_invoices_path, class: 'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' } %>
      <button class="modal-open btn btn-default">Import</button>
      <%= link_to 'Send Mails', send_emails_invoices_path, class:'btn bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded', method: :post, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>

  <div class="flex flex-wrap items-center justify-between">
    <table class="text-left w-full">
      <thead>
        <tr>
          <th class="px-4 py-2">ID</th>
          <th class="px-4 py-2">PO Number</th>
          <th class="px-4 py-2">Order Number</th>
          <th class="px-4 py-2">Supplier Name</th>
          <th class="px-4 py-2">Amount</th>
        </tr>
      </thead>
      <tbody>
        <% @invoices.each do |invoice| %>
          <tr>
            <td class="border px-4 py-2"><%= invoice.id %></td>
            <td class="border px-4 py-2"><%= invoice.po_number %></td>
            <td class="border px-4 py-2"><%= invoice.order_number %></td>
            <td class="border px-4 py-2"><%= invoice.supplier_name %></td>
            <td class="border px-4 py-2"><%= invoice.amount %></td>
        <%end%>
      </tbody>
    </table>
    <div class="modal opacity-0 pointer-events-none fixed w-full h-full top-0 left-0 flex items-center justify-center">
      <div class="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"></div>
      
      <div class="modal-container bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
        
        <div class="modal-close absolute top-0 right-0 cursor-pointer flex flex-col items-center mt-4 mr-4 text-white text-sm z-50">
          <svg class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
            <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
          </svg>
          <span class="text-sm">(Esc)</span>
        </div>

        <!-- Add margin if you want to see some of the overlay behind the modal-->
        <div class="modal-content py-4 text-left px-6">
          <!--Title-->
          <div class="flex justify-between items-center pb-3">
            <p class="text-2xl font-bold">Import invoices</p>
            <div class="modal-close cursor-pointer z-50">
              <svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
              </svg>
            </div>
          </div>

          <!--Body-->
          <%= form_with url: import_invoices_path do |f| %>
             <%= f.file_field 'invoice[file]', label: false%>
             <button class="px-4 bg-indigo-500 p-3 rounded-lg text-white hover:bg-indigo-400" type="submit">Go Go</button>
          <% end %>
        </div>
      </div>
    </div>


  <div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SupplierBot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>

  </head>

 <body class="bg-white">

  <% flash.each do |type, message| %>
    <% if type == "alert" %>
      <div class="bg-red-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
    <% if type == "notice" %>
      <div class="bg-green-500">
        <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
      </div>
    <% end %>
  <% end %>

    <header class="mb-4">
      <nav class="flex items-center justify-between flex-wrap bg-gray-100 py-3 lg:px-10 px-3 text-gray-700 border-b border-gray-400">
        <div class="flex items-center flex-no-shrink mr-6">
          <%= link_to "SupplierBot", root_path, class:"link text-xl tracking-tight font-semibold" %>
        </div>
        <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 border rounded text-grey border-gray-500 hover:text-gray-600 hover:border-gray-600">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
          </button>
        </div>
        <div class="w-full block lg:flex-1 lg:flex items-center text-center lg:text-left">
          <div class="lg:flex-grow">
            <%= link_to "Profiles", profiles_path, class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link" %>
            <%= link_to "Invoices", invoices_path, class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link" %>
          </div>
          <div class="w-full block lg:flex lg:flex-row lg:flex-1 mt-2 lg:mt-0 text-center lg:text-left lg:justify-end items-center">
            <% if user_signed_in? %>
             <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
            <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default block" %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>

    <main class="lg:px-10 px-4">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, multipart: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :body, class: "label" %>
    <%= form.text_area :body, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :feature_image, class: "label" %>
    <div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-dropzone-max-file-size="2" data-dropzone-max-files="1">
    <%= form.file_field :feature_image, direct_upload: true, data: { target: 'dropzone.input' } %>
    <div class="dropzone-msg dz-message needsclick text-gray-600">
      <h3 class="dropzone-msg-title">Drag here to upload or click here to browse</h3>
      <span class="dropzone-msg-desc text-sm">2 MB file size maximum. Allowed file types png, jpg.</span>
      </div>
    </div>
  </div>

  <div class="mb-6">
    <%= form.submit  class: "btn-default btn" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="max-w-2xl m-auto">
  <h1 class="text-3xl font-bold text-black mb-6">Edit Post</h1>

  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="max-w-6xl m-auto">
  <div class="flex items-center justify-between pb-4 mb-4 border-b">
    <h1 class="text-xl font-bold mb-0 uppercase text-gray-500">Posts</h1>
    <%= link_to "New Post", new_post_path, class: "btn btn-default" if user_signed_in? %>
  </div>

  <div class="flex flex-wrap items-center justify-between">
  <% @posts.each do |post| %>
    <article class="border rounded-lg lg:w-1/3 w-full">
      <%= link_to post do %>
        <%= image_tag post.feature_image if post.feature_image.present? %>
      <% end %>

      <div class="p-6">
        <h1 class="text-2xl font-bold"><%= link_to post.title, post %></h1>

        <div class="leading-normal text-lg">
          <%= post.body %>
        </div>

        <% if user_signed_in? && current_user.id == post.user_id %>
          <div class="my-4">
            <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %>
            <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
    </article>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="max-w-2xl m-auto">
  <h1 class="text-3xl font-bold text-black mb-6">New Post</h1>

  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="max-w-4xl m-auto">
  <%= link_to @post do %>
    <%= image_tag @post.feature_image if @post.feature_image.present? %>
  <% end %>

  <div class="p-6">
    <h1 class="text-2xl font-bold"><%= @post.title %></h1>

    <div class="leading-normal text-lg">
      <%= @post.body %>
    </div>

    <% if user_signed_in? && current_user.id == @post.user_id %>
      <div class="my-4">
        <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default" %>
        <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
    </div>
    <% end %>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="max-w-6xl m-auto">
  <div class="flex items-center justify-between pb-4 mb-4 border-b">
    <h1 class="text-xl font-bold mb-0 uppercase text-gray-500">Profiles</h1>
    <div>
      <%= link_to 'Delete All Data',destroy_all_profiles_path, class: 'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' } %>
      <button class="modal-open btn btn-default">Import</button>
    </div>
  </div>

  <div class="flex flex-wrap items-center justify-between">
    <table class="text-left w-full">
      <thead>
        <tr>
          <th class="px-4 py-2">ID</th>
          <th class="px-4 py-2">Company Name</th>
          <th class="px-4 py-2">Name</th>
          <th class="px-4 py-2">Email</th>
          <th class="px-4 py-2">Sub Email</th>
          <th class="px-4 py-2">Kind</th>
        </tr>
      </thead>
      <tbody>
        <% @profiles.each do |profile| %>
          <tr>
            <td class="border px-4 py-2"><%= profile.id %></td>
            <td class="border px-4 py-2"><%= profile.company_name %></td>
            <td class="border px-4 py-2"><%= profile.name %></td>
            <td class="border px-4 py-2"><%= profile.email %></td>
            <td class="border px-4 py-2"><%= profile.sub_email %></td>
            <td class="border px-4 py-2"><%= profile.kind %></td>
        <%end%>
      </tbody>
    </table>
    <div class="modal opacity-0 pointer-events-none fixed w-full h-full top-0 left-0 flex items-center justify-center">
      <div class="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"></div>
      
      <div class="modal-container bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
        
        <div class="modal-close absolute top-0 right-0 cursor-pointer flex flex-col items-center mt-4 mr-4 text-white text-sm z-50">
          <svg class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
            <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
          </svg>
          <span class="text-sm">(Esc)</span>
        </div>

        <!-- Add margin if you want to see some of the overlay behind the modal-->
        <div class="modal-content py-4 text-left px-6">
          <!--Title-->
          <div class="flex justify-between items-center pb-3">
            <p class="text-2xl font-bold">Import profiles</p>
            <div class="modal-close cursor-pointer z-50">
              <svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
              </svg>
            </div>
          </div>

          <!--Body-->
          <%= form_with url: import_profiles_path do |f| %>
             <%= f.file_field 'profile[file]', label: false%>
             <button class="px-4 bg-indigo-500 p-3 rounded-lg text-white hover:bg-indigo-400" type="submit">Go Go</button>
          <% end %>
        </div>
      </div>
    </div>


  <div>
</div>